 data = read.table(file="ca-caverage.xls",head=F)
 pdf("caverage.pdf",width=10,height=5)
  data = read.table(file="ca-caverage.xls",head=F)
 plot(data[,2],ylim=c(0,102),bty='u',type="p",pch=16,cex=1,xaxt="n",ylab="Frequency",yaxs='i',col="magenta",las=1, cex.axis=1,cex.lab=1,main="The coverage of Tumor",xlab="")  
 lines( data[,3] ,col="olivedrab2",bty='u',type="p",pch=16)
 lines( data[,4] ,col="orange",bty='u',type="p",pch=16)
 lines( data[,5] ,col="blue",bty='u',type="p",pch=16)  
 lines( data[,6] ,col="mediumseagreen",bty='u',type="p",pch=16) 
 lines( data[,7] ,col="red",bty='u',type="p",pch=16)
 legend("bottomright",legend=c("1X","10X","20X","50X","100X","200X"), pch=15,col=c("red","mediumseagreen","blue","orange","olivedrab2","magenta"),cex=1 )
axis(side=1,at = 1:27,labels = data[,1] ) 
 box()
 data = read.table(file="pl-caverage.xls",head=F)
 plot(data[,2],ylim=c(0,102),bty='u',type="p",pch=16,cex=1,xaxt="n",yaxs='i',col="magenta",las=1, cex.axis=1,cex.lab=1,ylab="Frequency",main="The coverage of ctDNA",xlab="")  
 lines( data[,3] ,col="olivedrab2",bty='u',type="p",pch=16)
 lines( data[,4] ,col="orange",bty='u',type="p",pch=16)
 lines( data[,5] ,col="blue",bty='u',type="p",pch=16)  
 lines( data[,6] ,col="mediumseagreen",bty='u',type="p",pch=16) 
 lines( data[,7] ,col="red",bty='u',type="p",pch=16)
 legend("bottomright",legend=c("1X","10X","20X","50X","100X","200X"), pch=15,col=c("red","mediumseagreen","blue","orange","olivedrab2","magenta"),cex=1 )
 axis(side=1,at = 1:27,labels = data[,1] ) 
 box()
 data = read.table(file="wbc-caverage.xls",head=F)
 plot(data[,2],ylim=c(0,102),bty='u',type="p",pch=16,cex=1,xaxt="n",yaxs='i',col="magenta",las=1, cex.axis=1,cex.lab=1,ylab="Frequency",main="The coverage of wbc",xlab="")  
 lines( data[,3] ,col="olivedrab2",bty='u',type="p",pch=16)
 lines( data[,4] ,col="orange",bty='u',type="p",pch=16)
 lines( data[,5] ,col="blue",bty='u',type="p",pch=16)  
 lines( data[,6] ,col="mediumseagreen",bty='u',type="p",pch=16) 
 lines( data[,7] ,col="red",bty='u',type="p",pch=16)
 legend("bottomright",legend=c("1X","10X","20X","50X","100X","200X"), pch=15,col=c("red","mediumseagreen","blue","orange","olivedrab2","magenta"),cex=1 )
 axis(side=1,at = 1:27,labels = data[,1] )  
box()
dev.off()



